'use client';

import React, { useState, useEffect } from 'react';
import { X, FileSpreadsheet, CheckCircle2, Download, Printer, Sparkles, Loader2, FileText } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

interface ReportGenerationModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const GENERATION_STEPS = [
  'Compiling workforce metrics...',
  'Analyzing competency trends across 6 wings...',
  'Summarizing high-priority skill gaps...',
  'Preparing strategic recommendations...',
  'Generating executive summary dossier...',
];

export function ReportGenerationModal({ isOpen, onClose }: ReportGenerationModalProps) {
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [isCompleted, setIsCompleted] = useState(false);
  const [isDownloaded, setIsDownloaded] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      setCurrentStepIndex(0);
      setIsCompleted(false);
      setIsDownloaded(false);
      return;
    }

    let step = 0;
    const interval = setInterval(() => {
      step += 1;
      if (step < GENERATION_STEPS.length) {
        setCurrentStepIndex(step);
      } else {
        clearInterval(interval);
        setIsCompleted(true);
      }
    }, 600);

    return () => clearInterval(interval);
  }, [isOpen]);

  if (!isOpen) return null;

  const handleDownload = () => {
    setIsDownloaded(true);
    // Create simple client-side text summary file download
    const reportText = `=====================================================
COMPETIQ — NATIONAL STATISTICAL SYSTEM
EXECUTIVE WORKFORCE INTELLIGENCE REPORT
Date: September 2026
Source: COMPETIQ Strategic Workforce Intelligence Console
=====================================================

1. WORKFORCE SUMMARY
- Total Statistical Officials: 12,540
- Active Learners (Q3): 8,231 (65.6% engagement)
- Overall Competency Score: 72%
- Critical Skill Deficit Rate: 18% (-2.6% QoQ)
- Learning Completion Rate: 76%

2. STRATEGIC COMPETENCY SHORTAGES
- AI / Machine Learning: 28% gap (5,130 affected officials)
- Python Scripting: 27% gap (4,820 affected officials)
- GIS & Geospatial Analysis: 22% gap (3,740 affected officials)
- Data Visualization & BI: 21% gap (3,420 affected officials)

3. PRIORITY DIRECTIVES
1. Launch Foundational AI Literacy & Anomaly Detection Track
2. Scale Python for Automation in Agricultural & Industrial Censuses
3. Deploy Geospatial Cadastral Mapping Certification with NRSC
4. Institutionalize Interactive Visual Dashboarding for Parliamentary Reporting

Generated by COMPETIQ Workforce Analytics
=====================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `COMPETIQ_Workforce_Intelligence_Report_${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-xs p-4 animate-in fade-in duration-200">
      <div
        className="w-full max-w-xl bg-surface border border-border rounded-2xl shadow-2xl p-6 sm:p-7 space-y-5 animate-in zoom-in-95 duration-200"
        role="dialog"
        aria-modal="true"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border-light pb-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary border border-primary/20 flex items-center justify-center">
              <FileSpreadsheet className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-text-primary">
                Generate Workforce Intelligence Report
              </h3>
              <p className="text-[11px] text-text-secondary">
                Executive briefing dossier for MoSPI &amp; National Statistical Commission
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-text-muted hover:text-text-primary hover:bg-surface-raised transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Progress or Completion View */}
        {!isCompleted ? (
          <div className="py-8 space-y-6 text-center">
            <div className="relative w-16 h-16 mx-auto flex items-center justify-center">
              <Loader2 className="w-12 h-12 text-primary animate-spin" />
              <Sparkles className="w-5 h-5 text-ai-purple absolute" />
            </div>

            <div className="space-y-2">
              <h4 className="text-sm font-bold text-text-primary">
                {GENERATION_STEPS[currentStepIndex]}
              </h4>
              <p className="text-xs text-text-muted">
                Step {currentStepIndex + 1} of {GENERATION_STEPS.length}
              </p>
            </div>

            {/* Progress Bar */}
            <div className="w-full bg-border-light rounded-full h-2 overflow-hidden max-w-md mx-auto">
              <div
                className="h-full bg-gradient-to-r from-primary to-teal transition-all duration-300"
                style={{
                  width: `${((currentStepIndex + 1) / GENERATION_STEPS.length) * 100}%`,
                }}
              />
            </div>
          </div>
        ) : (
          <div className="space-y-4 animate-in fade-in duration-300">
            {/* Success Banner */}
            <div className="p-3.5 bg-teal-light text-teal border border-teal/20 rounded-xl flex items-center gap-3">
              <CheckCircle2 className="w-5 h-5 text-teal shrink-0" />
              <div className="text-xs">
                <span className="font-bold text-teal block">
                  Workforce Intelligence Report Ready
                </span>
                <span className="text-teal/80">
                  Compiled from 12,540 assessed officials across all 6 statistical directorates.
                </span>
              </div>
            </div>

            {/* Executive Preview Card */}
            <div className="bg-surface-raised border border-border rounded-xl p-4 space-y-2.5 text-xs font-mono">
              <div className="flex items-center justify-between border-b border-border-light pb-2 font-bold text-text-primary">
                <span>Dossier: MoSPI-WIR-2026-Q3</span>
                <Badge variant="teal" size="sm">Verified Cadre Data</Badge>
              </div>

              <div className="grid grid-cols-2 gap-2 text-[11px] text-text-secondary">
                <div>Officials Assessed: <strong>12,540</strong></div>
                <div>Avg Competency: <strong>72%</strong></div>
                <div>Top Shortage: <strong>AI/ML (28% gap)</strong></div>
                <div>Active Learners: <strong>8,231 (65.6%)</strong></div>
              </div>

              <p className="text-[11px] text-text-muted pt-2 border-t border-border-light leading-relaxed">
                Contains executive charts, departmental deficit matrices, training effectiveness metrics, and prioritized capacity building roadmaps.
              </p>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row items-center justify-end gap-2 pt-3 border-t border-border-light">
              <Button variant="secondary" size="sm" onClick={onClose} className="w-full sm:w-auto text-xs">
                Close
              </Button>
              <Button
                variant="primary"
                size="sm"
                onClick={handleDownload}
                className="w-full sm:w-auto text-xs font-semibold gap-2"
              >
                <Download className="w-3.5 h-3.5" />
                {isDownloaded ? 'Downloaded Report' : 'Download Summary (.txt)'}
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
