'use client';

import React, { useState } from 'react';
import { StrategicRecommendationItem } from '@/data/workforceInsights';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { CheckCircle2, Users, TrendingUp, Sparkles, Clock, ArrowRight, ShieldCheck } from 'lucide-react';

interface StrategicRecommendationsListProps {
  initialRecommendations: StrategicRecommendationItem[];
  onSelectRecommendation?: (rec: StrategicRecommendationItem) => void;
}

export function StrategicRecommendationsList({
  initialRecommendations,
  onSelectRecommendation,
}: StrategicRecommendationsListProps) {
  const [recommendations, setRecommendations] = useState<StrategicRecommendationItem[]>(
    initialRecommendations
  );

  const handleMarkReviewed = (id: string) => {
    setRecommendations((prev) =>
      prev.map((rec) =>
        rec.id === id ? { ...rec, status: 'Reviewed' as const } : rec
      )
    );
  };

  const handleCreatePlan = (id: string) => {
    setRecommendations((prev) =>
      prev.map((rec) =>
        rec.id === id ? { ...rec, status: 'Action Planned' as const } : rec
      )
    );
  };

  const getStatusBadge = (status: StrategicRecommendationItem['status']) => {
    switch (status) {
      case 'Action Planned':
        return <Badge variant="success" size="sm" withDot>Action Planned</Badge>;
      case 'Reviewed':
        return <Badge variant="teal" size="sm" withDot>Reviewed</Badge>;
      case 'New':
      default:
        return <Badge variant="critical" size="sm" withDot>New Directive</Badge>;
    }
  };

  return (
    <div className="bg-surface border border-border rounded-2xl p-6 shadow-sm space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border-light pb-3">
        <div>
          <h3 className="text-base font-bold text-text-primary">
            Recommended Workforce Strategic Actions
          </h3>
          <p className="text-xs text-text-secondary mt-0.5">
            Prescriptive organizational interventions generated by competency analytics
          </p>
        </div>
        <span className="text-xs font-mono text-text-muted">
          {recommendations.length} Prioritized Directives
        </span>
      </div>

      <div className="space-y-3">
        {recommendations.map((rec) => (
          <div
            key={rec.id}
            className="p-4 bg-surface-raised border border-border rounded-xl flex flex-col md:flex-row md:items-center justify-between gap-4 hover:border-primary/40 transition-all"
          >
            <div className="space-y-1.5 max-w-2xl">
              <div className="flex items-center gap-2">
                <span className="w-5 h-5 rounded-full bg-primary text-white flex items-center justify-center font-bold text-xs font-mono shrink-0">
                  {rec.priorityOrder}
                </span>
                <h4 className="text-sm font-bold text-text-primary">
                  {rec.title}
                </h4>
                {getStatusBadge(rec.status)}
                <Badge variant={rec.impact === 'High' ? 'critical' : 'warning'} size="sm">
                  {rec.impact} Impact
                </Badge>
              </div>

              <p className="text-xs text-text-secondary leading-relaxed">
                {rec.summary}
              </p>

              <div className="flex flex-wrap items-center gap-4 text-xs font-mono text-text-muted pt-1">
                <span className="flex items-center gap-1">
                  <Users className="w-3.5 h-3.5 text-primary" />
                  <strong>{rec.affectedOfficials.toLocaleString()}</strong> officials
                </span>
                <span className="flex items-center gap-1 text-teal font-semibold">
                  <TrendingUp className="w-3.5 h-3.5" />
                  Uplift: {rec.expectedImprovement}
                </span>
                <span className="text-[11px] text-text-muted">
                  Cadre: {rec.targetCadres.join(', ')}
                </span>
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-wrap items-center gap-2 shrink-0 self-start md:self-center">
              {rec.status === 'New' && (
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => handleMarkReviewed(rec.id)}
                  className="text-xs h-8 px-2.5 font-medium"
                >
                  Mark as Reviewed
                </Button>
              )}

              {rec.status !== 'Action Planned' ? (
                <Button
                  variant="primary"
                  size="sm"
                  onClick={() => handleCreatePlan(rec.id)}
                  className="text-xs h-8 px-3 font-semibold gap-1.5"
                >
                  Create Training Plan
                  <ArrowRight className="w-3.5 h-3.5" />
                </Button>
              ) : (
                <div className="px-3 py-1 bg-teal-light text-teal border border-teal/20 rounded-lg text-xs font-semibold flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  In Planning Queue
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
