"""COMPETIQ Pydantic Schemas Package."""

from app.schemas.auth import (
    TokenPayload,
    TokenResponse,
    TokenUser,
    UserLogin,
    UserRegister,
)
from app.schemas.common import (
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    MessageResponse,
)
from app.schemas.competency import (
    CompetencyCreate,
    CompetencyResponse,
    CompetencyUpdate,
    RoleCompetencyRequirementCreate,
    RoleCompetencyRequirementResponse,
    RoleCompetencyRequirementUpdate,
    UserCompetencyCreate,
    UserCompetencyResponse,
    UserCompetencyUpdate,
)
from app.schemas.course import (
    CourseCompetencyCreate,
    CourseCompetencyResponse,
    CourseCreate,
    CoursePrerequisiteCreate,
    CoursePrerequisiteResponse,
    CourseResponse,
    CourseUpdate,
)
from app.schemas.learning_path import (
    LearningPathGenerationResponse,
    LearningPathItemBriefCourse,
    LearningPathItemResponse,
    LearningPathItemUpdate,
    LearningPathResponse,
)
from app.schemas.recommendation import CourseRecommendationResponse
from app.schemas.skill_gap import (
    OrganizationSkillGapSummaryResponse,
    SkillGapAnalysisResponse,
    SkillGapResponse,
    SkillGapSummary,
    TopSkillGap,
)
from app.schemas.onboarding import (
    AvailableCompetenciesResponse,
    BulkSkillDeclarationRequest,
    CompetencyDomainGroup,
    CompetencyDomainGroupResponse,
    CompetencyInitResponse,
    CompetencyItemResponse,
    CompetencyOption,
    InitializedCompetencyItem,
    OnboardingCompleteResponse,
    OnboardingStatusResponse,
    ProfileCreate,
    ProfileResponse,
    ProfileUpdate,
    RecommendedAssessmentResponse,
    SkillDeclarationCreate,
    SkillDeclarationResponse,
    SkillDeclarationUpdate,
    UserProfileSummaryResponse,
)
from app.schemas.user import (
    DepartmentBriefResponse,
    RoleBriefResponse,
    UserResponse,
)

__all__ = [
    "MessageResponse",
    "HealthResponse",
    "ErrorDetail",
    "ErrorResponse",
    "UserRegister",
    "UserLogin",
    "TokenUser",
    "TokenResponse",
    "TokenPayload",
    "UserResponse",
    "RoleBriefResponse",
    "DepartmentBriefResponse",
    "ProfileCreate",
    "ProfileUpdate",
    "ProfileResponse",
    "CompetencyOption",
    "CompetencyDomainGroup",
    "AvailableCompetenciesResponse",
    "SkillDeclarationCreate",
    "SkillDeclarationUpdate",
    "SkillDeclarationResponse",
    "BulkSkillDeclarationRequest",
    "OnboardingStatusResponse",
    "CompetencyItemResponse",
    "CompetencyDomainGroupResponse",
    "InitializedCompetencyItem",
    "CompetencyInitResponse",
    "OnboardingCompleteResponse",
    "RecommendedAssessmentResponse",
    "UserProfileSummaryResponse",
    "CompetencyCreate",
    "CompetencyUpdate",
    "CompetencyResponse",
    "UserCompetencyCreate",
    "UserCompetencyUpdate",
    "UserCompetencyResponse",
    "RoleCompetencyRequirementCreate",
    "RoleCompetencyRequirementUpdate",
    "RoleCompetencyRequirementResponse",
    "SkillGapResponse",
    "SkillGapSummary",
    "SkillGapAnalysisResponse",
    "TopSkillGap",
    "OrganizationSkillGapSummaryResponse",
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseCompetencyCreate",
    "CourseCompetencyResponse",
    "CoursePrerequisiteCreate",
    "CoursePrerequisiteResponse",
    "CourseRecommendationResponse",
    "LearningPathItemBriefCourse",
    "LearningPathItemResponse",
    "LearningPathItemUpdate",
    "LearningPathResponse",
    "LearningPathGenerationResponse",
]
